// Generated by CoffeeScript 1.3.3

/*
 * Description or Responsability
 *
 * @namespace KINOUT
 * @class Step
 *
 * @author Javier Jimenez Villar <javi@tapquo.com> || @soyjavi
*/


(function() {

  KINOUT.Step = (function(knt, undefined_) {
    /*
    */

    var hide, show;
    show = function() {
      return this;
    };
    /*
    */

    hide = function(horizontal_idx, vertical_idx) {};
    return {
      show: show,
      hide: hide
    };
  })(KINOUT);

}).call(this);
